package com.doing.in2019.in06.in28.Exception;

public class ReadMe {

	/** Excetpion -- 异常 */
	
	/** 首先，测试一下在正常代码里直接抛出会发生什么情况 (发现没，这个抛出没有要求捕获处理) */
	public static void main(String[] args) {
		throw new RuntimeException();
	}
	
	
	/**
	 * Java可分为三种异常
	 * 
	 * 
	 * 
	 */
}